spring:
  datasource:
    username: ${CONFIG_DATASOURCE_USERNAME}
    password: ${CONFIG_DATASOURCE_PASSWORD}
    url: ${CONFIG_DATASOURCE_URL}
    driver-class-name: ${CONFIG_DATASOURCE_DRIVER}
    hikari:
      minimumIdle: ${CONFIG_DATASOURCE_HIKARI_MINIMUM_IDLE}
      maximumPoolSize: ${CONFIG_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE}
  flyway:
    enabled: true