INSERT INTO MEMES (MEME) VALUES
	('People say nothing is impossible, but I do nothing every day.'),
	('Better to remain silent and be thought a fool than to speak out and remove all doubt.'),
	('Light travels faster than sound. This is why some people appear bright until you hear them speak.'),
	('Nobody realizes that some people expend tremendous energy merely to be normal.'),
	('Men marry women with the hope they will never change. Women marry men with the hope they will change. Invariably they are both disappointed.'),
	('The difference between stupidity and genius is that genius has its limits.'),
	('All the things I really like to do are either immoral, illegal or fattening.”'),
	('War is God’s way of teaching Americans geography.'),
	('It would be nice to spend billions on schools and roads, but right now that money is desperately needed for political ads.'),
	('If you want your children to listen, try talking softly to someone else.'),
	('I don’t believe in astrology; I’m a Sagittarius and we’re skeptical.'),
	('My opinions may have changed, but not the fact that I’m right.'),
	('To be sure of hitting the target, shoot first, and call whatever you hit the target.'),
	('Money won’t buy happiness, but it will pay the salaries of a large research staff to study the problem.'),
	('A bank is a place that will lend you money if you can prove that you don’t need it.'),
	('Inside me there’s a thin person struggling to get out, but I can usually sedate him with four or five cupcakes.'),
	('My favorite machine at the gym is the vending machine.'),
	('I always arrive late at the office, but I make up for it by leaving early.'),
	('Don’t worry about the world coming to an end today. It is already tomorrow in Australia.'),
	('Remember, today is the tomorrow you worried about yesterday.'),
	('Everyone has a purpose in life. Perhaps yours is watching television.'),
	('A pessimist is a person who has had to listen to too many optimists.'),
	('I’m in shape. Round is a shape.');